<html>

<head>
    <link rel="stylesheet" type="text/css" href="/style.css">
    <title>Home Page</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">
</head>

<body>

TESTING




<footer class="the_footer">
    <div>
        <h2>About us</h2>
        <p>This is a website demonstration</p>
    </div>
    <div>
        <h2>Contact Us</h2>
        <p>336-0000-0000</p>
    </div>
</footer>
</body>



</html>