<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel ="stylesheet" type="text/css" href="style.css">
    <title>Registration Page</title>
</head>
<body>
    <div class = "intro">   
        <a href ="landingPage.ftlh"><img src = "images/logo_2.png" class="logo"></a>
    </div>

    <div class="tutor_or_student">
        <h1>Are you a Tutor or a Student?</h1>
        <div class ="reg_choice">
            <div><a href="register-user.ftlh"><button class="student_choice">Student</button></a></div>
            <div><a href="registerTutor.ftlh"><button class="tutor_choice">Tutor</button></a></div>
        </div>
    </div>
    
    <footer class="the_footer">
        <div>
            <h2>About us</h2>
            <p>This is a website demonstration</p>
        </div>
        <div>
            <h2>Contact Us</h2>
            <p>336-0000-0000</p>
        </div>
    </footer>
</body>
</html>