<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tutelage - Registration Page</title>
    <link rel="stylesheet" href="/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>

<!-- Nav Bar -->
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000;">
    <a class="navbar-brand" href="/" style="margin: 10px;">
        <img src="/images/Tutelage.png" alt="Logo" width="80" height="60">
    </a>
    <ul class="nav justify-content-end">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/tutors/all">All Tutors</a>
        </li>
    </ul>
</nav>

<!-- Form for creating a new tutor -->
<div class="container mt-4">
    <h2>Registering As A Student or Tutor?:</h2>

    <div class="container-md">
        <a href="/tutors/create" class="btn btn-outline-danger">Tutor</a>
        <br>
        <a href="/students/customer-create" class="btn btn-outline-danger">Student</a>
    </div>

</div> <br>

</body>
</html>
